const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
 const options={headless:true};
 if(process.env.CHROMIUM_EXECUTABLE) options.executablePath=process.env.CHROMIUM_EXECUTABLE;
 if(process.env.CI || process.getuid?.()===0) options.args=['--no-sandbox','--disable-gpu','--disable-dev-shm-usage'];
 const browser=await chromium.launch(options);
 const page=await browser.newPage({viewport:{width:1060,height:1250},colorScheme:'light'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'..','index.html')).href);
 const f=page;
 await f.locator('#sscng-meeting').waitFor();
 await f.locator('#sg-version').fill('1.0.1');
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.match(await f.locator('#sg-form-error').textContent(),/already published/);
 await f.locator('#sg-version').fill('1.1.0');
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isEnabled(),true);
 await f.locator('#sg-review-note').fill('Please clarify the release notes.');
 await f.getByRole('button',{name:'Request changes',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isDisabled(),true);
 assert.doesNotMatch(await f.locator('#sg-review').textContent(),/unrecognized/);
 await f.getByRole('tab',{name:'1 · Metadata'}).click();
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isDisabled(),true);
 await f.getByRole('tab',{name:'1 · Metadata'}).click();
 await f.locator('#sg-notes').fill('Adds a missing-period check with a reproducible example.');
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isEnabled(),true);

 await f.getByRole('button',{name:'Approve demo release'}).click();
 assert.equal(await f.locator('#sg-version').isDisabled(),true);
 await f.getByRole('button',{name:'View package history'}).click();
 assert.equal(await f.locator('.sg-release').count(),3);
 await f.locator('[data-release="1.0.0"]').click();
 await f.getByRole('button',{name:'Restore 1.0.0 in demo'}).click();
 assert.match(await f.locator('#sg-history').textContent(),/Demo environment: 1.0.0/);
 await f.locator('[data-release="1.0.1"]').click();
 await f.locator('#sg-scenario').selectOption('dependency');
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isDisabled(),true);
 assert.match(await f.locator('#sg-review').textContent(),/Install passed/);
 await f.locator('#sg-review-note').fill('Declare the missing helper and rerun the example.');
 await f.getByRole('button',{name:'Request changes',exact:true}).click();
 await f.getByRole('button',{name:'Add missing dependency & rerun'}).click();
 assert.match(await f.locator('#sg-review').textContent(),/Revision 2/);
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).isEnabled(),true);
 await f.getByRole('tab',{name:'1 · Metadata'}).click();
 await f.locator('#sg-notes').fill('Updated notes after checks.');
 await f.getByRole('tab',{name:'2 · Checks & review'}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo release'}).count(),0);
 await f.locator('#sg-scenario').selectOption('transfer');
 await f.getByRole('button',{name:'Run demo checks',exact:true}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo transfer'}).isDisabled(),true);
 await f.getByRole('button',{name:'Simulate prior-owner confirmation'}).click();
 assert.equal(await f.getByRole('button',{name:'Approve demo transfer'}).isEnabled(),true);
 await f.getByRole('button',{name:'Approve demo transfer'}).click();
 await f.getByRole('button',{name:'View package history'}).click();
 assert.equal(await f.locator('.sg-release').count(),2);
 assert.match(await f.locator('#sg-history').textContent(),/Maintainer: Morgan Lee/);
 const frame=page.mainFrame();
 const checkWidth=async()=>frame.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,root:document.querySelector('#sscng-meeting').getBoundingClientRect().width}));
 assert.equal((await checkWidth()).width,(await checkWidth()).scroll,'Desktop overflow');
 await page.setViewportSize({width:375,height:1600});
 assert.equal((await checkWidth()).width,(await checkWidth()).scroll,'Mobile history overflow');
 await f.locator('#sg-scenario').selectOption('routine');
 assert.equal((await checkWidth()).width,(await checkWidth()).scroll,'Mobile form overflow');
 await page.emulateMedia({colorScheme:'dark'});
 await page.setViewportSize({width:1060,height:1250});
 assert.deepEqual(errors,[]);
 console.log('All interaction checks passed; no page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
